language: node_js
node_js:
  - node
  - lts/*
  - 10

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags

script:
  - yarn run build
  - yarn run test
  - yarn run test:e2e
  - yarn run lint

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: node

notifications:
  email:
    on_success: never
